### ISSUE TITLE
Out of bounds array write

### ISSUE THREAD

**Issue by Janrupf** [darlinghq/darlingserver#7]
This loop goes over `processor_count` and writes into `processor_array`, assuming `MAX_SCHED_CPUS` is less or equal to `get_nprocs_conf()`. However, on my system `get_nprocs_conf()` returns `128`, while `MAX_SCHED_CPUS` is 64, leading to memory corruption and finally process termination. 

https://github.com/darlinghq/darlingserver/blob/697fa6e643f0d7c44f5db2143f266345efb37136/duct-tape/src/processor.c#L39-L43

I'm not entirely sure if it is safe to just limit the iteration to `MAX_SCHED_CPUS` or if adjusting the macro makes more sense.

**Comment by facekapow** [comment]
Hey there, thanks for the bug report! Sorry for the delay.

We need to have an XNU `processor_t` for every available CPU (core) so that all CPUs work properly when queried by Mach traps, so adjusting the macro would be the better option. It seems that the existing XNU code should already be able to work with higher values, so we can change it to something like 256 to be safe for now; at least I don't know of any CPU (or multi-socket board) with more than 256 cores yet.

Feel free to submit a PR for that if you like :wink:

**Comment by Janrupf** [comment]
I just looked through the kernel source code and it appears that a limit of 64 processors is universally applied. The problem here is that in some places bitmasks of 64bits are used to identify processors, which means just increasing the macro wouldn't do the trick. Instead every use of the bitmasks would have to be replaced with a bigger bitmask.

The mask seems to be defined by `bitmap_t`, but I'm not entirely sure if this is consistently used everywhere.

Could limiting the processor's in this manner cause issues?:
```c
processor_count = get_nprocs_conf();
if (processor_count > MAX_SCHED_CPUS)
    processor_count = MAX_SCHED_CPUS;

processor_avail_count = get_nprocs();
if (processor_avail_count > MAX_SCHED_CPUS)
    processor_avail_count = MAX_SCHED_CPUS;

processor_avail_count_user = processor_avail_count;
```

**Comment by x3x7** [comment]
I can confirm that on machines with more than 64 cores "darling shell" command is crashing with message:
"Cannot open mnt namespace file: No such file or directory".

This is because the darlingserver process is crashing and the /proc/PIDofServer/ns/mnt is no longer available for the main program (darling).

MAX_SCHED_CPUS is defined in two places:
a. src/external/lkm/osfmk/kern/processor.h:297
b. src/external/darlingserver/duct-tape/xnu/osfmk/kern/processor.h:396

The 1st one is probably obsolete. Nevertheless I changed both of them to 128 and I was happy to see that darling shell was no longer crashing on start.

While the fix seems to work there is code in 
src/external/darlingserver/duct-tape/xnu/osfmk/kern/processor.c
making use of "bit_set" which is limited to 64bits. As it is implemented it works if the active cpu_id is less than 64. For larger values the bit_set function does not crash and does nothing.

As side issue, 128 upper limit is too small (the current hardware max is for AMD cpus with 384 for a dual socket 9654 Epyc Genoa).

**Comment by tihmstar** [comment]
I also just ran into the same issue.
Note, that _just_ increasing the macro is not an acceptable solution, as that wouldn't fix the underlying issue.

On my system `get_nprocs_conf()` returns a very large value (4096 iirc), despite only having 16 actual (logical) cores.
I suspect that this is the value that the kernel *could* handle. Practially speaking, for an application there is not difference between a non-existing core and a disabled core.
(Note: i'm running in a VM on Hyper-V)

The solution suggested by @Janrupf seems the best.
> Could limiting the processor's in this manner cause issues?:
> 
> ```c
> processor_count = get_nprocs_conf();
> if (processor_count > MAX_SCHED_CPUS)
>     processor_count = MAX_SCHED_CPUS;
> 
> processor_avail_count = get_nprocs();
> if (processor_avail_count > MAX_SCHED_CPUS)
>     processor_avail_count = MAX_SCHED_CPUS;
> 
> processor_avail_count_user = processor_avail_count;
> ```

**Comment by CuriousTommy** [comment]
Would anyone here be able to checkout my `fix_processor_count_out_of_bounds` branch, and verify that this works on their machine?

I don't have a machine with more then 64 cores to test this on...

**Comment by danix800** [comment]
We're trying the latest code on our 7995x with 192 cores, with `processor_count` limited to `MAX_SCHED_CPUS` the crash
goes away. I also think that `MAX_SCHED_CPUS = 64`  is too small.

@CuriousTommy You can also try lowering `MAX_SCHED_CPUS` to be smaller than your current available cpus to test this
issue. I can also reproduce it on my 20 cores laptop by setting `MAX_SCHED_CPUS` to 16, and by limiting
`processor_count` the crash goes away.

**Comment by CuriousTommy** [comment]
Thanks for the suggestion @danix800. I was able to reproduce the issue on my machine (and the fix provided by Janrupf resolves the issue).
